version: '3.8'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_USERNAME: 'devbills'
      MONGO_INITDB_PASSWORD: 'pass123'
    ports:
      - '27018:27017'  # Porta externa 27018 vinculada à interna 27017 do MongoDB
    volumes:
      - mongo-data:/data/db  # Volume persistente para os dados do MongoDB

  app:
    depends_on:
      - mongo
    container_name: devbills-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
    ports:
      - '3333:3333'  # Porta 3333 do seu host para 3333 do container (aplicação)

volumes:
  mongo-data:  # Volume persistente para os dados do MongoDB

networks:
  local:
    name: local
